name: 'Configure Inviwo Build environment'
description: 'Configure vcpkg and ccache'

inputs:
  triplet:
    description: 'Vcpkg triplet to use'
    required: true
  configuration:
    description: 'Configuration to use'
    required: true
  ccache:
    description: 'Setup ccache'
    required: false
    default: true
  gh-token:
    description: "github actions token for access to the octokit api to be able to remove onld caches"
    default: false
    required: false

runs:
  using: "composite"
  steps:
    - name: "Setup MSVC"
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: "Get Vcpkg SHA"
      shell: bash
      run: |
        SHA=`jq -r '.["vcpkg-configuration"].["default-registry"].baseline' inviwo/vcpkg.json`
        echo "VCPKG_SHA=${SHA}" >> $GITHUB_ENV

    - name: "Clone Vcpkg"
      uses: actions/checkout@v4
      with:
        repository: microsoft/vcpkg
        ref: ${{ env.VCPKG_SHA }}
        path: vcpkg

    - name: "VCPKG Update"
      shell: bash
      run: |
        cd vcpkg
        ./bootstrap-vcpkg.sh
        echo "VCPKG_INSTALLATION_ROOT=`pwd`" >> $GITHUB_ENV
        echo "VCPKG_ROOT=`pwd`" >> $GITHUB_ENV

    - name: "Create ccache directory"
      shell: bash
      run: |
        mkdir ccache-debug

    - name: "Setup Ccache"
      id: ccache
      if: inputs.ccache
      uses: petersteneteg/ccache-action@v2.4.0
      with:
        variant: ccache
        max-size: "1500M"
        verbose: 2
        save: "${{ github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'CI: Debug') }}"
        append-timestamp: true
        gh-token: ${{ inputs.gh-token }}
        key: inviwo-${{ inputs.triplet }}-${{ inputs.configuration }}
        restore-keys: |
          inviwo-${{ inputs.triplet }}-${{ inputs.configuration }}

    - name: "Copy ccache"
      shell: bash
      if: runner.os == 'Windows' && inputs.ccache
      run: |
        mkdir build
        cp ${{ steps.ccache.outputs.executable }} build/cl.exe
